// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoCsgMM0WiRo1RzDGaTTeA6aT__1AIz8',
    appId: '1:120611530859:web:98390465e71182a5e8a92e',
    messagingSenderId: '120611530859',
    projectId: 'namaaprojectapp',
    authDomain: 'namaaprojectapp.firebaseapp.com',
    storageBucket: 'namaaprojectapp.firebasestorage.app',
    measurementId: 'G-XZYW0VH857',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbzF4P5s6DuXw2APQODoWhQMLoGE81bx8',
    appId: '1:120611530859:android:31956a2b543d2ac4e8a92e',
    messagingSenderId: '120611530859',
    projectId: 'namaaprojectapp',
    storageBucket: 'namaaprojectapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUNUEbCyGi0qkG1zzNcMDIaUCeMfRSM8',
    appId: '1:120611530859:ios:059a48e0f10d3d10e8a92e',
    messagingSenderId: '120611530859',
    projectId: 'namaaprojectapp',
    storageBucket: 'namaaprojectapp.firebasestorage.app',
    iosBundleId: 'com.example.namaaProjectApp',
  );
}
