import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart';

// أمر لتشغيل السكريبت:
// flutter run lib/seed_store_products.dart

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final db = FirebaseFirestore.instance;

  final products = [
    {
      'name': 'حقيبة قماشية',
      'image': 'assets/images/products/natural_wicker_basket.png',
      'category': 'other',
      'price': 3.5,
      'stock': 50,
      'active': true,
      'desc': 'حقيبة قماشية قوية ومتينة قابلة لإعادة الاستخدام أكثر من 1000 مرة. مثالية للتسوق وتقليل استهلاك أكياس البلاستيك.',
      'emoji': '🛍️',
      'plastic': '50 غ',
    },
    {
      'name': 'مطرة مياه حرارية',
      'image': 'assets/images/products/thermal_water_bottle.png',
      'category': 'other',
      'price': 8.0,
      'stock': 30,
      'active': true,
      'desc': 'مطرة مياه صحية من الستانلس ستيل، تحفظ البرودة والحرارة لساعات، وتغنيك عن شراء زجاجات المياه البلاستيكية.',
      'emoji': '💧',
      'plastic': '25 غ',
    },
    {
      'name': 'مصابيح LED',
      'image': 'assets/images/products/energy_led_bulbs.png',
      'category': 'other',
      'price': 2.5,
      'stock': 100,
      'active': true,
      'desc': 'مصابيح موفرة للطاقة تدوم طويلاً، تقلل من فاتورة الكهرباء وتخفف الانبعاثات الكربونية.',
      'emoji': '💡',
      'plastic': '0 غ',
    },
    {
      'name': 'فرشاة البامبو',
      'image': 'assets/images/products/bamboo_toothbrush.png',
      'category': 'other',
      'price': 1.5,
      'stock': 120,
      'active': true,
      'desc': 'فرشاة أسنان مصنوعة من خشب البامبو الطبيعي القابل للتحلل 100%، بديل ممتاز للفرش البلاستيكية.',
      'emoji': '🪥',
      'plastic': '20 غ',
    },
    {
      'name': 'سلة خوص طبيعية',
      'image': 'assets/images/products/natural_wicker_basket.png',
      'category': 'other',
      'price': 12.0,
      'stock': 15,
      'active': true,
      'desc': 'سلة أنيقة من الخوص الطبيعي، مثالية للتخزين بدلاً من العبوات البلاستيكية، تضفي طابعاً طبيعياً للمنزل.',
      'emoji': '🧺',
      'plastic': '100 غ',
    },
    {
      'name': 'قوار نبات عضوي',
      'image': 'assets/images/products/eco_plant_pot.png',
      'category': 'pots',
      'price': 4.0,
      'stock': 60,
      'active': true,
      'desc': 'قوار نباتات مصنوع من مواد قابلة للتحلل وصديقة للبيئة، يسمح لجذور النباتات بالتنفس بشكل أفضل.',
      'emoji': '🪴',
      'plastic': '80 غ',
    },
    {
      'name': 'طقم مائدة خشبي',
      'image': 'assets/images/products/wooden_cutlery_set.png',
      'category': 'other',
      'price': 5.5,
      'stock': 40,
      'active': true,
      'desc': 'طقم شوك وملاعق من الخشب الطبيعي، خفيف الوزن ومناسب للسفر والرحلات، بديل للأدوات البلاستيكية.',
      'emoji': '🍴',
      'plastic': '15 غ',
    },
    {
      'name': 'كوب قهوة صديق',
      'image': 'assets/images/products/reusable_coffee_cups.png',
      'category': 'other',
      'price': 6.0,
      'stock': 35,
      'active': true,
      'desc': 'كوب قهوة أنيق قابل لإعادة الاستخدام، مصنوع من ألياف البامبو، خذ قهوتك معك دون الحاجة لأكواب ورقية مبطنة بالبلاستيك.',
      'emoji': '☕',
      'plastic': '10 غ',
    },
    {
      'name': 'قشات معدنية',
      'image': 'assets/images/products/metal_straws.png',
      'category': 'other',
      'price': 2.0,
      'stock': 200,
      'active': true,
      'desc': 'طقم قشات من الستانلس ستيل مع فرشاة تنظيف، وداعاً للقشات البلاستيكية ذات الاستخدام الواحد.',
      'emoji': '🥤',
      'plastic': '5 غ',
    },
    {
      'name': 'ليفة جلي طبيعية',
      'image': 'assets/images/products/natural_dish_sponge.png',
      'category': 'other',
      'price': 1.0,
      'stock': 150,
      'active': true,
      'desc': 'ليفة تنظيف الأواني مستخلصة من ألياف نباتية، تتخلصون منها بوضعها بالسماد العضوي بعد انتهاء عمرها.',
      'emoji': '🧽',
      'plastic': '10 غ',
    },
    {
      'name': 'قطع مكياج قطنية',
      'image': 'assets/images/products/washable_makeup_pads.png',
      'category': 'other',
      'price': 3.0,
      'stock': 80,
      'active': true,
      'desc': 'قطع غسيل بشرة ناعمة من القطن العضوي، قابلة للغسل وإعادة الاستخدام مئات المرات.',
      'emoji': '💄',
      'plastic': '2 غ',
    },
    {
      'name': 'صابون طبيعي صلب',
      'image': 'assets/images/products/natural_solid_soap.png',
      'category': 'other',
      'price': 2.5,
      'stock': 90,
      'active': true,
      'desc': 'صابون بخلاصات طبيعية وعلاجية بدون تغليف بلاستيكي، مناسب لجميع أنواع البشرة.',
      'emoji': '🧼',
      'plastic': '30 غ',
    },
    {
      'name': 'شامبو صلب',
      'image': 'assets/images/products/solid_shampoo_bar.png',
      'category': 'other',
      'price': 4.5,
      'stock': 70,
      'active': true,
      'desc': 'قطعة شامبو صلبة تعادل 3 زجاجات شامبو تقليدية، غنية بالزيوت المفيدة وبدون أي نفايات بلاستيكية.',
      'emoji': '💆',
      'plastic': '40 غ',
    },
    {
      'name': 'أكياس قمامة متحللة',
      'image': 'assets/images/products/biodegradable_trash_bags.png',
      'category': 'other',
      'price': 2.0,
      'stock': 150,
      'active': true,
      'desc': 'أكياس قمامة مصنوعة من نشا الذرة، تتحلل بالكامل في التربة ولا تترك أثراً بلاستيكياً.',
      'emoji': '🗑️',
      'plastic': '100 غ',
    },
    {
      'name': 'حوافظ طعام زجاج',
      'image': 'assets/images/products/glass_food_containers.png',
      'category': 'other',
      'price': 15.0,
      'stock': 25,
      'active': true,
      'desc': 'طقم من الحوافظ الزجاجية الصحية والآمنة لتخزين بقايا الطعام والمأكولات بالثلاجة.',
      'emoji': '🍱',
      'plastic': '150 غ',
    },
    {
      'name': 'أكياس سيليكون',
      'image': 'assets/images/products/silicone_food_bags.png',
      'category': 'other',
      'price': 5.0,
      'stock': 60,
      'active': true,
      'desc': 'أكياس سيليكون ممتازة الجودة، تغنيك كلياً عن أكياس التفريز البلاستيكية ذات الاستخدام الواحد.',
      'emoji': '🧊',
      'plastic': '10 غ',
    },
    {
      'name': 'أغطية شمع النحل',
      'image': 'assets/images/products/beeswax_food_wrap.png',
      'category': 'other',
      'price': 4.5,
      'stock': 85,
      'active': true,
      'desc': 'بديل صديق للبيئة للحفظ والتغليف، أغطية مصنوعة من القطن وشمع النحل وتتشكل بحرارة اليد.',
      'emoji': '🐝',
      'plastic': '15 غ',
    },
    {
      'name': 'ورق تواليت مدور',
      'image': 'assets/images/products/recycled_toilet_paper.png',
      'category': 'recycled',
      'price': 3.0,
      'stock': 100,
      'active': true,
      'desc': 'ورق تواليت مصنوع 100% من الورق المعاد تدويره بدون قطع أشجار جديدة.',
      'emoji': '🧻',
      'plastic': '0 غ',
    },
    {
      'name': 'منظفات منزلية',
      'image': 'assets/images/products/eco_house_cleaners.png',
      'category': 'other',
      'price': 6.5,
      'stock': 40,
      'active': true,
      'desc': 'مواد تنظيف بمكونات نباتية قوية على الأوساخ ولكنها آمنة وعطوفة على بيئتنا المائية.',
      'emoji': '✨',
      'plastic': '0 غ',
    },
    {
      'name': 'شاحن طاقة شمسية',
      'image': 'assets/images/products/solar_powered_charger.png',
      'category': 'other',
      'price': 18.0,
      'stock': 20,
      'active': true,
      'desc': 'بنك طاقة يشحن عبر ألواح شمسية مدمجة، حافظ على اتصالك واستفد من طاقة الشمس النظيفة.',
      'emoji': '☀️',
      'plastic': '0 غ',
    },
    {
      'name': 'حقيبة تسوق طي',
      'image': 'assets/images/products/foldable_shopping_bag.png',
      'category': 'other',
      'price': 2.5,
      'stock': 110,
      'active': true,
      'desc': 'حقيبة صغيرة جداً يمكنك حملها بميدالية المفاتيح لتكون دائماً جاهزاً لتسوق بدون أكياس نايلون.',
      'emoji': '👜',
      'plastic': '25 غ',
    },
    {
      'name': 'بذور نباتات محلية',
      'image': 'assets/images/products/plant_seeds.png',
      'category': 'seeds',
      'price': 1.0,
      'stock': 300,
      'active': true,
      'desc': 'مغلفات بذور سهلة الزراعة تناسب طقس منطقتنا لإضافة المساحات الخضراء والجمالية لبيئتك.',
      'emoji': '🌱',
      'plastic': '0 غ',
    },
    {
      'name': 'نبتة داخلية طبيعية',
      'image': 'assets/images/products/indoor_plant.png',
      'category': 'plants',
      'price': 15.0,
      'stock': 20,
      'active': true,
      'desc': 'نبتة منزليّة منعشة تنقي الهواء وتضفي لمسة من الطبيعة داخل منزلك.',
      'emoji': '🌿',
      'plastic': '0 غ',
    },
    {
      'name': 'شتلة شجرة برتقال',
      'image': 'assets/images/products/orange_sapling.png',
      'category': 'plants',
      'price': 22.0,
      'stock': 10,
      'active': true,
      'desc': 'شتلة شجرة غنية لزراعتها في حديقتك والمساهمة في بناء بيئة خضراء ومنتجة.',
      'emoji': '🍊',
      'plastic': '0 غ',
    },
    {
      'name': 'طقم معدات زراعية',
      'image': 'assets/images/products/gardening_tools.png',
      'category': 'tools',
      'price': 12.0,
      'stock': 35,
      'active': true,
      'desc': 'أدوات زراعية احترافية بمقابض خشبية متينة، مثالية للمساعدة في العناية بحديقتك.',
      'emoji': '🛠️',
      'plastic': '40 غ',
    },
    {
      'name': 'مرشة مياه معدنية',
      'image': 'assets/images/products/watering_can.png',
      'category': 'tools',
      'price': 8.5,
      'stock': 50,
      'active': true,
      'desc': 'مرشة مياه أنيقة وعملية مصنوعة من المعدن المقاوم للصدأ للري اليومي وتجنب المنتجات البلاستيكية.',
      'emoji': '🚿',
      'plastic': '25 غ',
    },
  ];

  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: const Text('جاري رفع المنتجات...')),
        body: Center(
          child: ElevatedButton(
            onPressed: () async {
              int count = 0;
              // حذف المنتجات القديمة أولاً لتجنب التكرار (اختياري)
              final oldProducts = await db.collection('products').get();
              for(var doc in oldProducts.docs) {
                await doc.reference.delete();
              }

              for (var p in products) {
                await db.collection('products').add(p);
                count++;
              }
              print('✅ تم إضافة $count منتجات بنجاح لمتجر نماء!');
            },
            child: const Text('رفع المنتجات إلى Firebase'),
          ),
        ),
      ),
    ),
  );
}
