// 🌱 سكريبت رفع المنتجات إلى Firestore
// تشغيل: dart run lib/store/seed_store_products.dart

import 'dart:io';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

const firebaseOptions = FirebaseOptions(
  apiKey: 'AIzaSyAbzF4P5s6DuXw2APQODoWhQMLoGE81bx8',
  appId: '1:120611530859:android:31956a2b543d2ac4e8a92e',
  messagingSenderId: '120611530859',
  projectId: 'namaaprojectapp',
  storageBucket: 'namaaprojectapp.firebasestorage.app',
);

const List<Map<String, dynamic>> _products = [
  {
    'name': 'حقيبة قماشية',
    'image': 'assets/images/products/eco_friendly_canvas_bag.png',
    'category': 'other',
    'price': 3.5,
    'stock': 50,
    'active': true,
    'desc': 'حقيبة قماشية قوية ومتينة قابلة لإعادة الاستخدام أكثر من 1000 مرة. مثالية للتسوق وتقليل استهلاك أكياس البلاستيك.',
    'emoji': '🛍️',
    'plastic': '50 غ',
  },
  {
    'name': 'فرشاة البامبو',
    'image': 'assets/images/products/bamboo_brush.png',
    'category': 'other',
    'price': 1.5,
    'stock': 120,
    'active': true,
    'desc': 'فرشاة أسنان مصنوعة من خشب البامبو الطبيعي القابل للتحلل 100%، بديل ممتاز للفرش البلاستيكية.',
    'emoji': '🪥',
    'plastic': '20 غ',
  },
  {
    'name': 'أغطية شمع النحل',
    'image': 'assets/images/products/beeswax_caps.png',
    'category': 'other',
    'price': 4.5,
    'stock': 85,
    'active': true,
    'desc': 'بديل صديق للبيئة للحفظ والتغليف، أغطية مصنوعة من القطن وشمع النحل وتتشكل بحرارة اليد.',
    'emoji': '🐝',
    'plastic': '15 غ',
  },
  {
    'name': 'ملحقات تقنية حيوية',
    'image': 'assets/images/products/bioplastic_phone_case.png',
    'category': 'recycled',
    'price': 5.5,
    'stock': 55,
    'active': true,
    'desc': 'أغطية هواتف مصنوعة من مخلفات المزارع قابلة للتحلل الحيوي.',
    'emoji': '📱',
    'plastic': '0 غ',
  },
  {
    'name': 'الصباريات والعصاريات',
    'image': 'assets/images/products/cacti_succulents.png',
    'category': 'plants',
    'price': 5.0,
    'stock': 100,
    'active': true,
    'desc': 'الخيار البديهي للبيئات الجافة. سقاية خفيفة كل أسبوعين تكفيها.',
    'emoji': '🌵',
    'plastic': '0 غ',
  },
  {
    'name': 'بيتموس جوز الهند',
    'image': 'assets/images/products/coco_coir_soil.png',
    'category': 'tools',
    'price': 4.5,
    'stock': 100,
    'active': true,
    'desc': 'بديل بيئي للبيتموس التقليدي، يحفظ الرطوبة بامتياز.',
    'emoji': '🥥',
    'plastic': '0 غ',
  },
  {
    'name': 'مرشة رذاذ زجاجية',
    'image': 'assets/images/products/glass_misting_bottle.png',
    'category': 'tools',
    'price': 6.5,
    'stock': 40,
    'active': true,
    'desc': 'مرشة زجاجية أنيقة لسقاية الأوراق وتوفير كميات المياه.',
    'emoji': '🧴',
    'plastic': '0 غ',
  },
  {
    'name': 'أكواب قشور القهوة',
    'image': 'assets/images/products/huskee_cup.png',
    'category': 'recycled',
    'price': 7.0,
    'stock': 40,
    'active': true,
    'desc': 'أكواب Huskee مصنوعة من قشور القهوة المعاد تدويرها. تدوير ذكي بعينه.',
    'emoji': '☕',
    'plastic': '0 غ',
  },
  {
    'name': 'صناديق الكومبوست للمطبخ',
    'image': 'assets/images/products/kitchen_compost_bin.png',
    'category': 'tools',
    'price': 22.0,
    'stock': 15,
    'active': true,
    'desc': 'صناديق صغيرة لتحويل مخلفات الطعام إلى سماد عضوي غني.',
    'emoji': '🗳️',
    'plastic': '100 غ',
  },
  {
    'name': 'بذور الخزامى',
    'image': 'assets/images/products/lavender_seeds.png',
    'category': 'seeds',
    'price': 2.5,
    'stock': 100,
    'active': true,
    'desc': 'نبات يحب الشمس ولا يطيق كثرة الماء. رائحته تساعد على الاسترخاء.',
    'emoji': '💜',
    'plastic': '0 غ',
  },
  {
    'name': 'مصابيح LED',
    'image': 'assets/images/products/led_lights.png',
    'category': 'other',
    'price': 2.5,
    'stock': 100,
    'active': true,
    'desc': 'مصابيح موفرة للطاقة تدوم طويلاً، تقلل من فاتورة الكهرباء وتخفف الانبعاثات الكربونية.',
    'emoji': '💡',
    'plastic': '0 غ',
  },
  {
    'name': 'مجموعات المايكروغرينز',
    'image': 'assets/images/products/microgreens_kit.png',
    'category': 'seeds',
    'price': 4.5,
    'stock': 80,
    'active': true,
    'desc': 'جرجير وفجل ينمو خلال 7-10 أيام فقط. لا يحتاج مساحة أو كميات ماء ضخمة.',
    'emoji': '🍱',
    'plastic': '0 غ',
  },
  {
    'name': 'طبقة الحصى والنشارة',
    'image': 'assets/images/products/mulch_pebbles.png',
    'category': 'tools',
    'price': 4.0,
    'stock': 100,
    'active': true,
    'desc': 'تمنع تبخر الماء بسرعة وتقلل عدد مرات السقاية بشكل ملحوظ.',
    'emoji': '🧱',
    'plastic': '0 غ',
  },
  {
    'name': 'سلة خوص طبيعية',
    'image': 'assets/images/products/natural_wicker_basket.png',
    'category': 'other',
    'price': 12.0,
    'stock': 15,
    'active': true,
    'desc': 'سلة أنيقة من الخوص الطبيعي، مثالية للتخزين بدلاً من العبوات البلاستيكية.',
    'emoji': '🧺',
    'plastic': '100 غ',
  },
  {
    'name': 'حقائب بلاستيك المحيطات',
    'image': 'assets/images/products/ocean_plastic_bag.png',
    'category': 'recycled',
    'price': 25.0,
    'stock': 25,
    'active': true,
    'desc': 'حقيبة ظهر مصنوعة من زجاجات البلاستيك الملقاة في البحار.',
    'emoji': '🌊',
    'plastic': '500 غ',
  },
  {
    'name': 'أصص ألياف طبيعية',
    'image': 'assets/images/products/organic_plant_pot.png',
    'category': 'pots',
    'price': 7.5,
    'stock': 45,
    'active': true,
    'desc': 'أصص مستدامة مصنوعة من مواد نباتية قابلة للتحلل الحيوي.',
    'emoji': '🎍',
    'plastic': '0 غ',
  },
  {
    'name': 'تربة معززة بالبرلايت',
    'image': 'assets/images/products/perlite_soil.png',
    'category': 'tools',
    'price': 5.5,
    'stock': 80,
    'active': true,
    'desc': 'صخور بركانية طبيعية تضمن تصريفاً مثالياً وتمنع هدر الماء.',
    'emoji': '⚪',
    'plastic': '0 غ',
  },
  {
    'name': 'منسوجات منزلية مدورة',
    'image': 'assets/images/products/recycled_home_textiles.png',
    'category': 'recycled',
    'price': 10.0,
    'stock': 40,
    'active': true,
    'desc': 'منسوجات حمام ومطبخ من مزيج القطن العضوي والبوليستر المعاد تدويره.',
    'emoji': '🧼',
    'plastic': '0 غ',
  },
  {
    'name': 'حذاء زجاجات البلاستيك',
    'image': 'assets/images/products/recycled_sneakers.png',
    'category': 'recycled',
    'price': 45.0,
    'stock': 10,
    'active': true,
    'desc': 'أحذية رياضية مصنوعة من خيوط تدوير زجاجات المياه البلاستيكية.',
    'emoji': '👟',
    'plastic': '0 غ',
  },
  {
    'name': 'المنسوجات المجددة',
    'image': 'assets/images/products/recycled_textiles.png',
    'category': 'recycled',
    'price': 9.5,
    'stock': 35,
    'active': true,
    'desc': 'أقمشة من القطن المعاد تدويره وخيوط الخيزران. مورد متجدد بامتياز.',
    'emoji': '🧵',
    'plastic': '0 غ',
  },
  {
    'name': 'ساعة خشب مدور',
    'image': 'assets/images/products/recycled_watch.png',
    'category': 'recycled',
    'price': 55.0,
    'stock': 5,
    'active': true,
    'desc': 'ساعات مصنوعة من خشب الأثاث القديم أو ألياف الكربون المعاد تدويرها.',
    'emoji': '⌚',
    'plastic': '0 غ',
  },
  {
    'name': 'مقياس رطوبة التربة',
    'image': 'assets/images/products/soil_moisture_meter.png',
    'category': 'tools',
    'price': 8.5,
    'stock': 35,
    'active': true,
    'desc': 'جهاز بلا بطاريات يخبرك بمستوى رطوبة التربة لمنع السقاية الزائدة.',
    'emoji': '📉',
    'plastic': '0 غ',
  },
  {
    'name': 'نبات العنكبوت',
    'image': 'assets/images/products/spider_plant.png',
    'category': 'plants',
    'price': 7.0,
    'stock': 45,
    'active': true,
    'desc': 'حيوي وسهل التكاثر. فعال جداً في امتصاص الروائح وتنقية الأبخرة المنزلية.',
    'emoji': '🕷️',
    'plastic': '0 غ',
  },
  {
    'name': 'بذور دوار الشمس',
    'image': 'assets/images/products/sunflower_seeds.png',
    'category': 'seeds',
    'price': 1.0,
    'stock': 500,
    'active': true,
    'desc': 'بذور قوية تنمو بسرعة وتدعم التلقيح.',
    'emoji': '🌻',
    'plastic': '0 غ',
  },
  {
    'name': 'مطرة مياه حرارية',
    'image': 'assets/images/products/thermal_water_rain.png',
    'category': 'other',
    'price': 8.0,
    'stock': 30,
    'active': true,
    'desc': 'مطرة مياه تقلل استهلاك البلاستيك وتحفظ الحرارة.',
    'emoji': '💧',
    'plastic': '25 غ',
  },
  {
    'name': 'بذور الزعتر',
    'image': 'assets/images/products/thyme_seeds.png',
    'category': 'seeds',
    'price': 1.5,
    'stock': 120,
    'active': true,
    'desc': 'نبات عنيد وجميل لا يحتاج لعناية كبيرة.',
    'emoji': '🌿',
    'plastic': '0 غ',
  },
  {
    'name': 'عبوات معدنية معاد تدويرها',
    'image': 'assets/images/products/upcycled_metal_cans.png',
    'category': 'recycled',
    'price': 12.0,
    'stock': 20,
    'active': true,
    'desc': 'عبوات قديمة تم صقلها لتتحول إلى قطع زينة فخمة.',
    'emoji': '🥫',
    'plastic': '0 غ',
  },
  {
    'name': 'كرات السقاية الزجاجية',
    'image': 'assets/images/products/watering_globes.png',
    'category': 'tools',
    'price': 12.0,
    'stock': 20,
    'active': true,
    'desc': 'تفرغ الماء ببطء شديد حسب حاجة النبات.',
    'emoji': '🔮',
    'plastic': '0 غ',
  },
  {
    'name': 'طقم مائدة خشبي',
    'image': 'assets/images/products/wooden_tableware_set.png',
    'category': 'other',
    'price': 5.5,
    'stock': 40,
    'active': true,
    'desc': 'طقم شوك وملاعق من الخشب الطبيعي.',
    'emoji': '🍴',
    'plastic': '15 غ',
  },
  {
    'name': 'نبات الزاميا',
    'image': 'assets/images/products/zz_plant.png',
    'category': 'plants',
    'price': 15.0,
    'stock': 20,
    'active': true,
    'desc': 'سيقانه تخزن الماء بكفاءة عالية، صديق للبيئة.',
    'emoji': '🌿',
    'plastic': '0 غ',
  },
];

Future<void> seedDatabase() async {
  print('🚀 بدأت عملية رفع المنتجات...');

  try {
    final db = FirebaseFirestore.instance;

    print('🧹 تنظيف المنتجات القديمة...');
    final oldDocs = await db.collection('products').get();
    
    // استخدام الحذف المتسلسل بدلاً من Batch لتفادي خطأ 500 عنصر الأقصى
    var count = 0;
    for (final doc in oldDocs.docs) {
      await doc.reference.delete();
      count++;
    }
    print('🧹 تم تنظيف $count منتج قديم...');

    print('🆕 رفع ${_products.length} منتج...');
    final addBatch = db.batch();
    for (final p in _products) {
      addBatch.set(db.collection('products').doc(), p);
    }
    await addBatch.commit();

    print('✅ تم بنجاح! إجمالي المنتجات: ${_products.length}');
  } catch (e) {
    print('❌ حدث خطأ كبير: $e');
  }
}